#Gender Constants
MALE = 'MALE'
FEMALE = 'FEMALE'
OTHER = 'OTHER'

#UserType Constants
ADMIN = 'ADMIN'
FIRM_ADMIN = 'FIRM_ADMIN'
FIRM_USER = 'FIRM_USER'
SUPERSELLER_USER = 'SUPERSELLER_USER'
DISTRIBUTOR_USER = 'DISTRIBUTOR_USER'
SALES_PERSON = 'SALES_PERSON'

#API Constants
POST = "POST"
PUT = "PUT"
DELETE = "DELETE"
GET = "GET"
GETALL = "GETALL"
PATCH = "PATCH"

